name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Робот берет твой код из GitHub

      - name: Copy docker-compose.yml to server
        uses: appleboy/scp-action@v0.1.4  # Робот копирует файл на сервер
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "docker-compose.yml"
          target: "/root/microservices-shop"

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.10 # Робот запускает команды на сервере
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/microservices-shop
            docker compose pull
            docker compose up -d